import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeaderNavbar from "./components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center min-h-screen px-4 font-mono bg-gray-900 ">
        <section className="max-w-xl ">
          <HeaderNavbar />
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </section>
      </main>
    </div>
  );
}
